packages:
  # all packages in subdirs of packages/ and components/
  - "packages/core"
  - "packages/ui"
  - "packages/transports/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
