/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * server - version 1
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.GetExample': ['GET', '/example/{id}'],
  'general.CreateExample': ['POST', '/example'],
  'general.UploadFile': ['POST', '/example/uploadFile'],
  'general.Create': ['POST', '/users'],
  'general.FindMany': ['GET', '/users'],
  'general.Find': ['GET', '/users/{id}'],
  'general.Update': ['PATCH', '/users/{id}'],
  'general.Delete': ['DELETE', '/users/{id}'],
  'general.FindMany': ['GET', '/contacts/{ownerId}'],
  'general.FindAll': ['GET', '/contacts'],
  'general.Create': ['POST', '/contacts'],
  'general.Update': ['PATCH', '/contacts/{id}'],
  'general.Delete': ['DELETE', '/contacts/{id}'],
  'general.Create': ['POST', '/calls'],
  'general.FindMany': ['GET', '/calls'],
  'general.Update': ['PATCH', '/calls/{id}'],
  'general.Find': ['GET', '/calls/{id}'],
  'general.Delete': ['DELETE', '/calls/{id}']
};
